spring:
  application:
    name: chat


  datasource:
    url: jdbc:postgresql://localhost:5433/chat062
    username: django062
    password: secretkey
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


application:
  security:
    jwt:
      security-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000
server:
  port: 8086