application:
  security:
    jwt:
      security-key: WmFxYXRhbGExOTkwMjAxODIwMTkyMDIyTWFoaXJBeWxpbjkwT3g5NjJIYXlhbGxlckFtZXJpa2FIYXlhdGxhcg==
      expiration: 86400000
      refresh-token:
        expiration: 604800000


server:
  port: 8086
  address: 0.0.0.0

spring:
  application:
    name: chat