
app:
  kafka:
    producer:
      topic: "my_first_topic"


spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
        max.block.ms: 20000
        delivery.timeout.ms: 30000

    consumer:
      bootstrap-servers: ${KAFKA_HOST_NAME:localhost}:${KAFKA_PORT:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: kafka-group-id
      auto-offset-reset: earliest
      fetch-max-wait: 500
      fetch-min-size: 1
      enable-auto-commit: false


    admin:
      properties:
        bootstrap.servers: ${KAFKA_HOST_NAME:localhost}:9092


